# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8971b002a9633f61e6b9cf4b0c1e444a6bac79d05adb82ca01bb94ed69458ecea1b9b530f3aef602bf43d24a4805b6fed4e3efc6925a1ca8c18fc8dee08403b5

test:
  secret_key_base: ee88c8f8ecf4ff4275b4da383731c66264a22c36e3a576c3b8170e93cade987f0ef98e2482a13f197d6bd3fa61fa8cf30ec2d80db5eb9627f671b3f0c9f12e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
